### ISSUE TITLE
Add Payment Type Filters

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#19] opened 2022-08-30 11:36 UTC
It would be cool to be able to filter my payment type. e.g. Onchain, Lightning, Lightning NFC.

**Comment by bubelov** [comment] 2022-09-03 08:23
Definitely, as soon as this information becomes widely available. Currently, there is nothing to filter. I'd say 500 LN/NFC-enabled places is a fair threshold.

**Comment by secondl1ght** [comment] 2022-10-02 13:03
Duplicate of https://github.com/teambtcmap/btcmap.org/issues/20

**Comment by dadofsambonzuki** [comment] 2022-10-03 20:39
Not a dupe. This is for Android.

**Closed** 2023-02-08 07:56 UTC
Labels: enhancement
