### ISSUE TITLE
Bug: Place name is not url encoded

### ISSUE THREAD

**Issue by andrei-21** [teambtcmap/btcmap-android#28] opened 2022-10-31 12:56 UTC
Place names in links to verify or report places are not properly URL encoded.
The problem is present for the Android and Web app.

 # Steps to reproduce
1. Find `Hotel Sole e Mare 72 Viale Ermenegildo Pistelli, Lido di Camaiore`
2. Click on `Verify or report`
3. URL `https://btcmap.org/report-outdated-info?&name=Hotel Sole e Mare&lat=43.895007050000004&long=10.2246128&way=127867294` is opened in a browser and search results shown 

# Actual behavior 
Search results for `https://btcmap.org/report-outdated-info?&name=Hotel Sole e Mare&lat=43.895007050000004&long=10.2246128&way=127867294` shown
# Expected behavior
`https://btcmap.org/verify-location?&name=Hotel%20Sole%20e%20Mare&lat=43.895007050000004&long=10.2246128&way=127867294` (mind `%20`) website is open

**Comment by bubelov** [comment] 2022-11-01 03:58
Can't reproduce

![Screenshot from 2022-11-01 10-56-05](https://user-images.githubusercontent.com/1189245/199155534-5ca624bc-4f1a-47fd-bfe9-136c54375d6e.png)


Anyway, no other params should be passed except for place ID, which is url-safe. There is a pending issue about that, I'll strip the rest of the args once they become unnecessary. Let's keep the issue open as a reminder.

**Comment by dadofsambonzuki** [comment] 2023-04-24 13:09
We can now update both apps to use the new place ID, right?

**Comment by secondl1ght** [comment] 2023-05-17 05:15
The Verify form now supports accepting an element `id` as the single param - we just need the mobile clients to update to this standard now and then we can close this issue. (I don't know if iOS app has a Verify button?)

Example: `http://localhost:5173/verify-location?id=node:7159146385`

**Comment by bubelov** [comment] 2023-05-18 01:10
Fixed in https://github.com/teambtcmap/btcmap-android/commit/0a6990d94184e179ee3744424e36855c56ae4cfe

**Closed by bubelov** 2023-05-18 01:10 UTC
Labels: bug
